export const LOAD = "LOAD";
export const LOADMORE = "LOADMORE";
export const ADD = "ADD";
export const SELECT = "SELECT";
export const CLEAR_SELECT = "CLEAR_SELECT";
export const UPDATE = "UPDATE";
export const REMOVE = "REMOVE";

export const LOADSESSIONS = "LOADSESSIONS";
export const ADDSESSION = "ADDSESSION";
export const ISSESSION = "ISSESSION";
export const SELECTSESSION = "SELECTSESSION";
export const SETSELSESSION = "SETSELSESSION";

export const VENUEDISPLAY = "VENUEDISPLAY";
export const SETSELECTEDVENUE = "SETSELECTEDVENUE";
export const ADDVENUE = "ADDVENUE";
export const LOADVENUE = "LOADVENUE";
export const SETNEWVENUENAME = "SETNEWVENUENAME";

export const WEBLINKDISPLAY = "WEBLINKDISPLAY";
export const LOADWEBLINKS = "LOADWEBLINKS";
export const ADDWEBLINKS = "ADDWEBLINKS";
export const SELECTWEBLINK = "SELECTWEBLINK";
export const SETSELWEBLINK = "SETSELWEBLINK";

export const SESSIONTYPEDISPLAY = "SESSIONTYPEDISPLAY";
export const LOADSESSIONTYPES = "LOADSESSIONTYPES";
export const ADDSESSIONTYPES = "ADDSESSIONTYPES";
export const SELECTSESSIONTYPE = "SELECTSESSIONTYPE";
export const SETSELSESSIONTYPE = "SETSELSESSIONTYPE";

export const PEOPLEDISPLAY = "PEOPLEDISPLAY";
export const LOADPEOPLES = "LOADPEOPLES";
export const ADDPEOPLES = "ADDPEOPLES";
export const SELECTPEOPLE = "SELECTPEOPLE";
export const SETSELPEOPLE = "SETSELPEOPLE";
export const WEBLINKPOPULATE = "WEBLINKPOPULATE";
export const PEOPLEPOPULATE = "PEOPLEPOPULATE";
export const VENUPOPULATE = "VENUPOPULATE";
export const SESSIONTYPEPOPULATE = "SESSIONTYPEPOPULATE";
export const UPDATE_EVENT = "UPDATE_EVENT"

export const UPDATEEVENTPEOPLE = "UPDATEEVENTPEOPLE"
export const UPDATEEVENTWEBLINK = "UPDATEEVENTWEBLINK"
export const UPDATEEVENTVENUE = "UPDATEEVENTVENUE"
export const UPDATEEVENTSESSIONTYPE = "UPDATEEVENTSESSIONTYPE"